"""add_client_management_tables

Revision ID: 1690096c1980
Revises: b88c5db5ac09
Create Date: 2025-12-16 10:39:23.504618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1690096c1980'
down_revision = 'b88c5db5ac09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('business_type', sa.Enum('INDIVIDUAL', 'PRIVATE_LIMITED', 'LLP', 'PARTNERSHIP', name='businesstype', native_enum=False, length=50), nullable=False),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'TERMINATED', name='clientstatus', native_enum=False, length=20), nullable=False, server_default='active'),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pin_code', sa.String(), nullable=True),
    sa.Column('onboard_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('follow_date', sa.Date(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_name'), 'clients', ['client_name'], unique=False)
    op.create_index(op.f('ix_clients_company_name'), 'clients', ['company_name'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_phone_number'), 'clients', ['phone_number'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('client_services',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'service_id')
    )
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('director_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('resignation', sa.String(), nullable=True),
    sa.Column('din', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('aadhaar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directors_client_id'), 'directors', ['client_id'], unique=False)
    op.create_index(op.f('ix_directors_id'), 'directors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directors_id'), table_name='directors')
    op.drop_index(op.f('ix_directors_client_id'), table_name='directors')
    op.drop_table('directors')
    op.drop_table('client_services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_clients_phone_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_company_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###

