"""Add address fields to organizations table

Revision ID: b88c5db5ac09
Revises: a748a6f2f6c3
Create Date: 2025-11-29 13:49:37.974251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88c5db5ac09'
down_revision = 'a748a6f2f6c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('city', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('country', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('pincode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'pincode')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    # ### end Alembic commands ###

