"""add_email_templates_table

Revision ID: fee4256af709
Revises: 15a133deb77a
Create Date: 2025-12-24 20:31:11.588674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee4256af709'
down_revision = '15a133deb77a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('SERVICE', 'LOGIN', 'NOTIFICATION', 'FOLLOW_UP', 'REMINDER', name='emailtemplatecategory', native_enum=False, length=50), nullable=False),
    sa.Column('type', sa.Enum('GST_FILING', 'INCOME_TAX_RETURN', 'TDS', 'AUDIT', 'COMPANY_REGISTRATION', 'TAX_PLANNING', 'COMPLIANCES', 'OTHER', name='emailtemplatetype', native_enum=False, length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('master_template_id', sa.Integer(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['master_template_id'], ['email_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_category'), 'email_templates', ['category'], unique=False)
    op.create_index(op.f('ix_email_templates_created_by'), 'email_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_index(op.f('ix_email_templates_is_default'), 'email_templates', ['is_default'], unique=False)
    op.create_index(op.f('ix_email_templates_master_template_id'), 'email_templates', ['master_template_id'], unique=False)
    op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=False)
    op.create_index(op.f('ix_email_templates_org_id'), 'email_templates', ['org_id'], unique=False)
    op.create_index(op.f('ix_email_templates_type'), 'email_templates', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_type'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_org_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_master_template_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_is_default'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_created_by'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_category'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###

